import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { useLanguage } from "@/i18n/LanguageContext";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { ShoppingCart, Trash2, Minus, Plus, ShoppingBag } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { useState } from "react";
import type { useCart } from "@/hooks/useCart";
import { useNavigate } from "react-router-dom";

interface CartSheetProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  cart: ReturnType<typeof useCart>;
}

export function CartSheet({ open, onOpenChange, cart }: CartSheetProps) {
  const { language } = useLanguage();
  const { user } = useAuth();
  const isAr = language === "ar";
  const navigate = useNavigate();
  const [isPlacing, setIsPlacing] = useState(false);

  const handlePlaceOrder = async () => {
    if (!user || cart.items.length === 0) return;

    setIsPlacing(true);
    try {
      // Create order
      const { data: order, error: orderError } = await supabase
        .from("shop_orders")
        .insert({
          buyer_id: user.id,
          total_amount: cart.totalPrice,
          currency: cart.items[0]?.currency || "USD",
          order_number: "", // Will be auto-generated by trigger
        })
        .select("id, order_number")
        .single();

      if (orderError) throw orderError;

      // Create order items
      const items = cart.items.map((item) => ({
        order_id: order.id,
        product_id: item.product_id,
        quantity: item.quantity,
        unit_price: item.price,
        total_price: item.price * item.quantity,
        product_snapshot: {
          title: item.title,
          title_ar: item.title_ar,
          image_url: item.image_url,
        },
      }));

      const { error: itemsError } = await supabase
        .from("shop_order_items")
        .insert(items);

      if (itemsError) throw itemsError;

      cart.clearCart();
      onOpenChange(false);
      toast({
        title: isAr ? "تم تقديم الطلب بنجاح!" : "Order placed successfully!",
        description: isAr
          ? `رقم الطلب: ${order.order_number}`
          : `Order number: ${order.order_number}`,
      });
      navigate("/shop/orders");
    } catch (error: any) {
      toast({
        title: isAr ? "خطأ في تقديم الطلب" : "Error placing order",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setIsPlacing(false);
    }
  };

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side={isAr ? "left" : "right"} className="flex w-full flex-col sm:max-w-md">
        <SheetHeader>
          <SheetTitle className="flex items-center gap-2">
            <ShoppingCart className="h-5 w-5" />
            {isAr ? "سلة التسوق" : "Shopping Cart"}
            {cart.totalItems > 0 && (
              <Badge variant="secondary">{cart.totalItems}</Badge>
            )}
          </SheetTitle>
        </SheetHeader>

        {cart.items.length === 0 ? (
          <div className="flex flex-1 flex-col items-center justify-center text-center">
            <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-muted/60">
              <ShoppingBag className="h-8 w-8 text-muted-foreground/40" />
            </div>
            <p className="font-medium">{isAr ? "السلة فارغة" : "Your cart is empty"}</p>
            <p className="mt-1 text-sm text-muted-foreground">
              {isAr ? "أضف منتجات لتبدأ التسوق" : "Add products to start shopping"}
            </p>
          </div>
        ) : (
          <>
            <div className="flex-1 space-y-3 overflow-y-auto py-4">
              {cart.items.map((item) => {
                const title = isAr && item.title_ar ? item.title_ar : item.title;
                return (
                  <div key={item.product_id} className="flex gap-3 rounded-lg border p-3">
                    <div className="h-16 w-16 shrink-0 overflow-hidden rounded-md bg-muted">
                      {item.image_url ? (
                        <img src={item.image_url} alt={title} className="h-full w-full object-cover" />
                      ) : (
                        <div className="flex h-full items-center justify-center">
                          <ShoppingBag className="h-6 w-6 text-muted-foreground/30" />
                        </div>
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium line-clamp-1">{title}</p>
                      <p className="text-sm font-bold text-primary">
                        {item.currency} {item.price.toFixed(2)}
                      </p>
                      <div className="mt-1.5 flex items-center gap-2">
                        <div className="flex items-center rounded border">
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-7 w-7"
                            onClick={() => cart.updateQuantity(item.product_id, item.quantity - 1)}
                          >
                            <Minus className="h-3 w-3" />
                          </Button>
                          <span className="w-7 text-center text-xs">{item.quantity}</span>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-7 w-7"
                            onClick={() => cart.updateQuantity(item.product_id, item.quantity + 1)}
                            disabled={item.quantity >= item.stock_quantity}
                          >
                            <Plus className="h-3 w-3" />
                          </Button>
                        </div>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-7 w-7 text-destructive"
                          onClick={() => cart.removeItem(item.product_id)}
                        >
                          <Trash2 className="h-3.5 w-3.5" />
                        </Button>
                      </div>
                    </div>
                    <p className="text-sm font-semibold shrink-0">
                      {item.currency} {(item.price * item.quantity).toFixed(2)}
                    </p>
                  </div>
                );
              })}
            </div>

            <div className="border-t pt-4 space-y-3">
              <div className="flex items-center justify-between text-lg font-bold">
                <span>{isAr ? "المجموع" : "Total"}</span>
                <span className="text-primary">
                  {cart.items[0]?.currency || "USD"} {cart.totalPrice.toFixed(2)}
                </span>
              </div>
              <Button
                className="w-full"
                size="lg"
                onClick={handlePlaceOrder}
                disabled={isPlacing}
              >
                {isPlacing
                  ? (isAr ? "جارٍ تقديم الطلب..." : "Placing order...")
                  : (isAr ? "تقديم الطلب" : "Place Order")}
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="w-full"
                onClick={() => cart.clearCart()}
              >
                <Trash2 className="me-1.5 h-3.5 w-3.5" />
                {isAr ? "إفراغ السلة" : "Clear Cart"}
              </Button>
            </div>
          </>
        )}
      </SheetContent>
    </Sheet>
  );
}
