project_id = "pbjhffdnzlekprmxfbnt"

[functions.ai-knowledge]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.judge-ai-assistant]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false

[functions.broadcast-notification]
verify_jwt = false
