-- Add whatsapp field to profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS whatsapp TEXT;

-- Drop and recreate profiles_public view to include whatsapp
DROP VIEW IF EXISTS public.profiles_public;

CREATE VIEW public.profiles_public AS
SELECT id,
    user_id,
    full_name,
    full_name_ar,
    display_name,
    display_name_ar,
    avatar_url,
    cover_image_url,
    bio,
    bio_ar,
    username,
    account_number,
    account_status,
    specialization,
    specialization_ar,
    experience_level,
    location,
    city,
    country_code,
    nationality,
    second_nationality,
    show_nationality,
    website,
    instagram,
    twitter,
    facebook,
    linkedin,
    youtube,
    tiktok,
    snapchat,
    whatsapp,
    preferred_language,
    profile_completed,
    membership_tier,
    membership_status,
    membership_expires_at,
    is_verified,
    verified_at,
    verification_level,
    verification_badge,
    gender,
    education_level,
    education_institution,
    years_of_experience,
    education_entity_id,
    section_visibility,
    offers_services,
    services_description,
    services_description_ar,
    global_awards,
    profile_visibility,
    job_title,
    job_title_ar,
    company_id,
    company_role,
    view_count,
    follow_privacy,
    created_at,
    updated_at
   FROM profiles;