
-- Create event series for Food Africa
INSERT INTO event_series (id, name, name_ar, description, description_ar, series_type, is_active, default_venue, default_venue_ar, default_city, default_country, default_organizer_name, default_organizer_name_ar, cover_image_url, website_url)
VALUES (
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'Food Africa',
  'فوود آفريكا',
  'Food Africa is the leading international food & beverage trade exhibition in Africa, connecting global food industry players with the African market.',
  'فوود آفريكا هو المعرض التجاري الدولي الرائد للأغذية والمشروبات في أفريقيا، يربط اللاعبين العالميين في صناعة الأغذية بالسوق الأفريقي.',
  'annual',
  true,
  'Egypt International Exhibition Center (EIEC)',
  'مركز مصر للمعارض الدولية',
  'Cairo',
  'Egypt',
  'IFP Group / Informa Markets',
  'مجموعة IFP / إنفورما ماركتس',
  NULL,
  'https://www.foodafrica-expo.com'
);

-- Update Food Africa 2026 to link to series
UPDATE exhibitions SET series_id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', edition_year = 2026 WHERE slug = 'food-africa-2026-mlzsxk8m';

-- Create previous editions
INSERT INTO exhibitions (id, title, title_ar, slug, description, description_ar, type, status, start_date, end_date, venue, venue_ar, city, country, edition_year, series_id, organizer_name, organizer_name_ar, organizer_id, edition_stats, view_count, is_featured)
VALUES
(
  gen_random_uuid(),
  'Food Africa 2025',
  'فوود آفريكا ٢٠٢٥',
  'food-africa-2025-edition',
  'The 8th edition of Food Africa brought together over 500 exhibitors from 45 countries, showcasing the latest in food technology, ingredients, and processing.',
  'الدورة الثامنة من فوود آفريكا جمعت أكثر من 500 عارض من 45 دولة، لعرض أحدث تقنيات وتكنولوجيا الأغذية والمكونات والتصنيع.',
  'exhibition',
  'completed',
  '2025-12-03 00:00:00+00',
  '2025-12-05 00:00:00+00',
  'Egypt International Exhibition Center (EIEC)',
  'مركز مصر للمعارض الدولية',
  'Cairo',
  'Egypt',
  2025,
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'IFP Group / Informa Markets',
  'مجموعة IFP / إنفورما ماركتس',
  (SELECT id FROM organizers WHERE slug LIKE '%ifp%' LIMIT 1),
  '{"visitors": 35000, "exhibitors": 520, "countries": 45, "area": 25000}'::jsonb,
  12500,
  false
),
(
  gen_random_uuid(),
  'Food Africa 2024',
  'فوود آفريكا ٢٠٢٤',
  'food-africa-2024-edition',
  'The 7th edition saw record attendance with innovative food processing solutions and sustainable packaging technologies taking center stage.',
  'شهدت الدورة السابعة حضوراً قياسياً مع حلول مبتكرة لتصنيع الأغذية وتقنيات التعبئة المستدامة.',
  'exhibition',
  'completed',
  '2024-12-04 00:00:00+00',
  '2024-12-06 00:00:00+00',
  'Egypt International Exhibition Center (EIEC)',
  'مركز مصر للمعارض الدولية',
  'Cairo',
  'Egypt',
  2024,
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'IFP Group / Informa Markets',
  'مجموعة IFP / إنفورما ماركتس',
  (SELECT id FROM organizers WHERE slug LIKE '%ifp%' LIMIT 1),
  '{"visitors": 30000, "exhibitors": 480, "countries": 42, "area": 22000}'::jsonb,
  10800,
  false
),
(
  gen_random_uuid(),
  'Food Africa 2023',
  'فوود آفريكا ٢٠٢٣',
  'food-africa-2023-edition',
  'The 6th edition marked a strong post-pandemic recovery with focus on food security and African agricultural exports.',
  'شكلت الدورة السادسة تعافياً قوياً بعد الجائحة مع التركيز على الأمن الغذائي والصادرات الزراعية الأفريقية.',
  'exhibition',
  'completed',
  '2023-12-05 00:00:00+00',
  '2023-12-07 00:00:00+00',
  'Egypt International Exhibition Center (EIEC)',
  'مركز مصر للمعارض الدولية',
  'Cairo',
  'Egypt',
  2023,
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'IFP Group / Informa Markets',
  'مجموعة IFP / إنفورما ماركتس',
  (SELECT id FROM organizers WHERE slug LIKE '%ifp%' LIMIT 1),
  '{"visitors": 25000, "exhibitors": 400, "countries": 38, "area": 20000}'::jsonb,
  8500,
  false
),
(
  gen_random_uuid(),
  'Food Africa 2022',
  'فوود آفريكا ٢٠٢٢',
  'food-africa-2022-edition',
  'The 5th edition returned with renewed energy, featuring specialized pavilions for organic food, halal products, and African specialties.',
  'عادت الدورة الخامسة بطاقة متجددة، مع أجنحة متخصصة للأغذية العضوية والمنتجات الحلال والتخصصات الأفريقية.',
  'exhibition',
  'completed',
  '2022-12-06 00:00:00+00',
  '2022-12-08 00:00:00+00',
  'Egypt International Exhibition Center (EIEC)',
  'مركز مصر للمعارض الدولية',
  'Cairo',
  'Egypt',
  2022,
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'IFP Group / Informa Markets',
  'مجموعة IFP / إنفورما ماركتس',
  (SELECT id FROM organizers WHERE slug LIKE '%ifp%' LIMIT 1),
  '{"visitors": 18000, "exhibitors": 350, "countries": 35, "area": 18000}'::jsonb,
  6200,
  false
);
