import type { ImportedData } from "@/components/smart-import/SmartImportDialog";
import type { TargetTable } from "@/components/smart-import/types";

export const buildEntityPayload = (d: ImportedData) => {
  const payload: Record<string, any> = {};
  if (d.name_en) payload.name = d.name_en;
  if (d.name_ar) payload.name_ar = d.name_ar;
  if (d.abbreviation_en) payload.abbreviation = d.abbreviation_en;
  if (d.abbreviation_ar) payload.abbreviation_ar = d.abbreviation_ar;
  if (d.description_en) payload.description = d.description_en;
  if (d.description_ar) payload.description_ar = d.description_ar;
  if (d.mission_en) payload.mission = d.mission_en;
  if (d.mission_ar) payload.mission_ar = d.mission_ar;
  if (d.phone) payload.phone = d.phone;
  if (d.fax) payload.fax = d.fax;
  if (d.email) payload.email = d.email;
  if (d.website) payload.website = d.website;
  if (d.city_en || d.city_ar) payload.city = d.city_en || d.city_ar;
  if (d.country_en || d.country_ar) payload.country = d.country_en || d.country_ar;
  if (d.full_address_en) payload.address = d.full_address_en;
  if (d.full_address_ar) payload.address_ar = d.full_address_ar;
  if (d.postal_code) payload.postal_code = d.postal_code;
  if (d.region_en) payload.region = d.region_en;
  if (d.region_ar) payload.region_ar = d.region_ar;
  if (d.district_en) payload.district = d.district_en;
  if (d.district_ar) payload.district_ar = d.district_ar;
  if (d.street_en) payload.street = d.street_en;
  if (d.street_ar) payload.street_ar = d.street_ar;
  if (d.building_number) payload.building_number = d.building_number;
  if (d.floor_number) payload.floor_number = d.floor_number;
  if (d.additional_number) payload.additional_number = d.additional_number;
  if (d.unit_number) payload.unit_number = d.unit_number;
  if (d.short_address) payload.short_address = d.short_address;
  if (d.latitude) payload.latitude = d.latitude;
  if (d.longitude) payload.longitude = d.longitude;
  if (d.registration_number) payload.registration_number = d.registration_number;
  if (d.license_number) payload.license_number = d.license_number;
  if (d.founded_year) payload.founded_year = d.founded_year;
  if (d.president_name_en) payload.president_name = d.president_name_en;
  if (d.president_name_ar) payload.president_name_ar = d.president_name_ar;
  if (d.secretary_name_en) payload.secretary_name = d.secretary_name_en;
  if (d.secretary_name_ar) payload.secretary_name_ar = d.secretary_name_ar;
  if (d.member_count) payload.member_count = d.member_count;
  const services = [...(d.services_en || []), ...(d.services_ar || [])].filter(Boolean);
  if (services.length) payload.services = services;
  const specs = [...(d.specializations_en || []), ...(d.specializations_ar || [])].filter(Boolean);
  if (specs.length) payload.specializations = specs;
  if (d.affiliated_organizations?.length) payload.affiliated_organizations = d.affiliated_organizations;
  if (d.tags?.length) payload.tags = d.tags;
  if (d.social_media && Object.values(d.social_media).some(Boolean)) payload.social_links = d.social_media;
  if (d.logo_url) payload.logo_url = d.logo_url;
  if (d.cover_url) payload.cover_image_url = d.cover_url;
  if (d.google_maps_url) payload.google_maps_url = d.google_maps_url;
  return payload;
};

export const buildCompanyPayload = (d: ImportedData) => {
  const payload: Record<string, any> = {};
  if (d.name_en) payload.name = d.name_en;
  if (d.name_ar) payload.name_ar = d.name_ar;
  if (d.description_en) payload.description = d.description_en;
  if (d.description_ar) payload.description_ar = d.description_ar;
  if (d.phone) payload.phone = d.phone;
  if (d.phone_secondary) payload.phone_secondary = d.phone_secondary;
  if (d.fax) payload.fax = d.fax;
  if (d.email) payload.email = d.email;
  if (d.website) payload.website = d.website;
  if (d.city_en || d.city_ar) payload.city = d.city_en || d.city_ar;
  if (d.country_en || d.country_ar) payload.country = d.country_en || d.country_ar;
  if (d.full_address_en) payload.address = d.full_address_en;
  if (d.full_address_ar) payload.address_ar = d.full_address_ar;
  if (d.postal_code) payload.postal_code = d.postal_code;
  if (d.region_en) payload.region = d.region_en;
  if (d.region_ar) payload.region_ar = d.region_ar;
  if (d.district_en) payload.district = d.district_en;
  if (d.district_ar) payload.district_ar = d.district_ar;
  if (d.street_en) payload.street = d.street_en;
  if (d.street_ar) payload.street_ar = d.street_ar;
  if (d.building_number) payload.building_number = d.building_number;
  if (d.floor_number) payload.floor_number = d.floor_number;
  if (d.additional_number) payload.additional_number = d.additional_number;
  if (d.unit_number) payload.unit_number = d.unit_number;
  if (d.short_address) payload.short_address = d.short_address;
  if (d.registration_number) payload.registration_number = d.registration_number;
  if (d.founded_year) payload.founded_year = d.founded_year;
  if (d.business_hours) payload.working_hours = d.business_hours;
  if (d.latitude) payload.latitude = d.latitude;
  if (d.longitude) payload.longitude = d.longitude;
  if (d.neighborhood_en) payload.neighborhood = d.neighborhood_en;
  if (d.neighborhood_ar) payload.neighborhood_ar = d.neighborhood_ar;
  if (d.street_en) payload.street = d.street_en;
  if (d.street_ar) payload.street_ar = d.street_ar;
  if (d.google_maps_url) payload.google_maps_url = d.google_maps_url;
  if (d.rating) payload.rating = d.rating;
  if (d.total_reviews) payload.total_reviews = d.total_reviews;
  if (d.national_id) payload.national_address = d.national_id;
  const specs = [...(d.specializations_en || []), ...(d.specializations_ar || [])].filter(Boolean);
  if (specs.length) payload.specializations = specs;
  if (d.social_media && Object.values(d.social_media).some(Boolean)) payload.social_links = d.social_media;
  if (d.description_en || d.business_type_en) payload.tagline = d.business_type_en || d.description_en?.substring(0, 100);
  if (d.logo_url) payload.logo_url = d.logo_url;
  if (d.cover_url) payload.cover_image_url = d.cover_url;
  payload.import_source = 'smart_import';
  return payload;
};

export const buildEstablishmentPayload = (d: ImportedData) => {
  const payload: Record<string, any> = {};
  if (d.name_en) payload.name = d.name_en;
  if (d.name_ar) payload.name_ar = d.name_ar;
  if (d.description_en) payload.description = d.description_en;
  if (d.description_ar) payload.description_ar = d.description_ar;
  if (d.phone) payload.phone = d.phone;
  if (d.email) payload.email = d.email;
  if (d.website) payload.website = d.website;
  if (d.city_en || d.city_ar) payload.city = d.city_en || d.city_ar;
  if (d.city_ar) payload.city_ar = d.city_ar;
  if (d.country_code) payload.country_code = d.country_code;
  if (d.full_address_en) payload.address = d.full_address_en;
  if (d.full_address_ar) payload.address_ar = d.full_address_ar;
  if (d.region_en) payload.region = d.region_en;
  if (d.region_ar) payload.region_ar = d.region_ar;
  if (d.district_en) payload.district = d.district_en;
  if (d.district_ar) payload.district_ar = d.district_ar;
  if (d.building_number) payload.building_number = d.building_number;
  if (d.floor_number) payload.floor_number = d.floor_number;
  if (d.additional_number) payload.additional_number = d.additional_number;
  if (d.unit_number) payload.unit_number = d.unit_number;
  if (d.short_address) payload.short_address = d.short_address;
  if (d.business_type_en) payload.cuisine_type = d.business_type_en;
  if (d.business_type_ar) payload.cuisine_type_ar = d.business_type_ar;
  if (d.rating) payload.star_rating = Math.round(d.rating);
  if (d.logo_url) payload.logo_url = d.logo_url;
  if (d.cover_url) payload.cover_image_url = d.cover_url;
  if (d.latitude) payload.latitude = d.latitude;
  if (d.longitude) payload.longitude = d.longitude;
  if (d.country_code) payload.country_code = d.country_code;
  if (d.google_maps_url) payload.google_maps_url = d.google_maps_url;
  if (d.social_media && Object.values(d.social_media).some(Boolean)) payload.social_links = d.social_media;
  return payload;
};

export const buildExhibitionPayload = (d: ImportedData) => {
  const payload: Record<string, any> = {};
  if (d.name_en) payload.title = d.name_en;
  if (d.name_ar) payload.title_ar = d.name_ar;
  if (d.description_long_en || d.description_en) payload.description = d.description_long_en || d.description_en;
  if (d.description_long_ar || d.description_ar) payload.description_ar = d.description_long_ar || d.description_ar;
  if (d.city_en || d.city_ar) payload.city = d.city_en || d.city_ar;
  if (d.country_en || d.country_ar) payload.country = d.country_en || d.country_ar;
  if (d.full_address_en) payload.address = d.full_address_en;
  if (d.full_address_ar) payload.address_ar = d.full_address_ar;
  if (d.region_en) payload.region = d.region_en;
  if (d.region_ar) payload.region_ar = d.region_ar;
  if (d.district_en) payload.district = d.district_en;
  if (d.district_ar) payload.district_ar = d.district_ar;
  if (d.postal_code) payload.postal_code = d.postal_code;
  if (d.building_number) payload.building_number = d.building_number;
  if (d.floor_number) payload.floor_number = d.floor_number;
  if (d.additional_number) payload.additional_number = d.additional_number;
  if (d.unit_number) payload.unit_number = d.unit_number;
  if (d.short_address) payload.short_address = d.short_address;
  if (d.venue_en) payload.venue = d.venue_en;
  if (d.venue_ar) payload.venue_ar = d.venue_ar;
  if (d.organizer_phone) payload.organizer_phone = d.organizer_phone;
  if (d.phone) payload.organizer_phone = d.phone;
  if (d.organizer_email || d.email) payload.organizer_email = d.organizer_email || d.email;
  if (d.website) payload.website_url = d.website;
  if (d.cover_url) payload.cover_image_url = d.cover_url;
  if (d.logo_url) payload.logo_url = d.logo_url;
  if (d.tags?.length) payload.tags = d.tags;
  if (d.social_media && Object.values(d.social_media).some(Boolean)) payload.social_links = d.social_media;
  if (d.registration_url) payload.registration_url = d.registration_url;
  if (d.registration_deadline) payload.registration_deadline = d.registration_deadline;
  if (d.max_attendees) payload.max_attendees = d.max_attendees;
  if (d.organizer_name_en) payload.organizer_name = d.organizer_name_en;
  if (d.organizer_name_ar) payload.organizer_name_ar = d.organizer_name_ar;
  if (d.organizer_logo_url) payload.organizer_logo_url = d.organizer_logo_url;
  if (d.organizer_website) payload.organizer_website = d.organizer_website;
  if (d.map_url) payload.map_url = d.map_url;
  if (d.ticket_price) payload.ticket_price = d.ticket_price;
  if (d.is_free !== undefined && d.is_free !== null) payload.is_free = d.is_free;
  if (d.is_virtual !== undefined && d.is_virtual !== null) payload.is_virtual = d.is_virtual;
  if (d.virtual_link) payload.virtual_link = d.virtual_link;
  if (d.target_audience?.length) payload.target_audience = d.target_audience;
  if (d.targeted_sectors?.length) payload.targeted_sectors = d.targeted_sectors;
  if (d.categories?.length) payload.categories = d.categories;
  if (d.edition_year) payload.edition_year = d.edition_year;
  if (d.currency) payload.currency = d.currency;
  if (d.early_bird_deadline) payload.early_bird_deadline = d.early_bird_deadline;
  if (d.gallery_urls?.length) payload.gallery_urls = d.gallery_urls;
  if (d.includes_competitions !== undefined) payload.includes_competitions = d.includes_competitions;
  if (d.includes_seminars !== undefined) payload.includes_seminars = d.includes_seminars;
  if (d.includes_training !== undefined) payload.includes_training = d.includes_training;
  if (d.reasons_to_attend?.length) payload.reasons_to_attend = d.reasons_to_attend;
  if (d.unique_features?.length) payload.unique_features = d.unique_features;
  if (d.highlights?.length) payload.highlights = d.highlights;
  if (d.edition_stats && Object.values(d.edition_stats).some(v => v !== null)) payload.edition_stats = d.edition_stats;
  if (d.entry_details && Object.values(d.entry_details).some(v => v !== null)) payload.entry_details = d.entry_details;
  if (d.venue_details && Object.values(d.venue_details).some(v => v !== null)) payload.venue_details = d.venue_details;
  if (d.sponsors?.length) payload.sponsors_info = d.sponsors;
  if (d.speakers?.length) payload.speakers = d.speakers;
  if (d.schedule_items?.length) payload.schedule = d.schedule_items;
  payload.import_source = 'smart_import';
  return payload;
};

export const buildCompetitionPayload = (d: ImportedData) => {
  const payload: Record<string, any> = {};
  if (d.name_en) payload.title = d.name_en;
  if (d.name_ar) payload.title_ar = d.name_ar;
  if (d.description_en) payload.description = d.description_en;
  if (d.description_ar) payload.description_ar = d.description_ar;
  if (d.city_en || d.city_ar) payload.city = d.city_en || d.city_ar;
  if (d.country_en || d.country_ar) payload.country = d.country_en || d.country_ar;
  if (d.country_code) payload.country_code = d.country_code;
  if (d.cover_url) payload.cover_image_url = d.cover_url;
  if (d.logo_url) payload.logo_url = d.logo_url;
  if (d.venue_en) payload.venue = d.venue_en;
  if (d.venue_ar) payload.venue_ar = d.venue_ar;
  if (d.max_attendees) payload.max_participants = d.max_attendees;
  if (d.registration_fee) payload.registration_fee = d.registration_fee;
  if (d.registration_url) payload.registration_url = d.registration_url;
  if (d.registration_deadline) payload.registration_deadline = d.registration_deadline;
  if (d.rules_summary_en) payload.rules_summary = d.rules_summary_en;
  if (d.rules_summary_ar) payload.rules_summary_ar = d.rules_summary_ar;
  if (d.terms_conditions_en) payload.terms_conditions = d.terms_conditions_en;
  if (d.terms_conditions_ar) payload.terms_conditions_ar = d.terms_conditions_ar;
  if (d.eligibility_en) payload.eligibility = d.eligibility_en;
  if (d.eligibility_ar) payload.eligibility_ar = d.eligibility_ar;
  if (d.scoring_method_en) payload.scoring_method = d.scoring_method_en;
  if (d.scoring_method_ar) payload.scoring_method_ar = d.scoring_method_ar;
  if (d.blind_judging !== undefined && d.blind_judging !== null) payload.blind_judging = d.blind_judging;
  if (d.max_team_size) payload.max_team_size = d.max_team_size;
  if (d.min_team_size) payload.min_team_size = d.min_team_size;
  if (d.competition_type) payload.competition_type = d.competition_type;
  if (d.age_restrictions) payload.age_restrictions = d.age_restrictions;
  if (d.dress_code) payload.dress_code = d.dress_code;
  if (d.dress_code_ar) payload.dress_code_ar = d.dress_code_ar;
  if (d.competition_versions?.length) payload.versions = d.competition_versions;
  if (d.judging_criteria?.length) payload.judging_criteria = d.judging_criteria;
  if (d.prizes?.length) payload.prizes = d.prizes;
  if (d.competition_rounds?.length) payload.rounds = d.competition_rounds;
  if (d.equipment_provided?.length) payload.equipment_provided = d.equipment_provided;
  if (d.equipment_required?.length) payload.equipment_required = d.equipment_required;
  if (d.participation_requirements_en?.length) payload.participation_requirements = d.participation_requirements_en;
  if (d.allowed_entry_types?.length) payload.allowed_entry_types = d.allowed_entry_types;
  if (d.website) payload.website_url = d.website;
  if (d.email) payload.email = d.email;
  if (d.phone) payload.phone = d.phone;
  if (d.social_media && Object.values(d.social_media).some(Boolean)) payload.social_links = d.social_media;
  if (d.tags?.length) payload.tags = d.tags;
  if (d.gallery_urls?.length) payload.gallery_urls = d.gallery_urls;
  if (d.latitude) payload.latitude = d.latitude;
  if (d.longitude) payload.longitude = d.longitude;
  if (d.google_maps_url) payload.google_maps_url = d.google_maps_url;
  if (d.full_address_en) payload.address = d.full_address_en;
  if (d.full_address_ar) payload.address_ar = d.full_address_ar;
  if (d.is_virtual !== undefined && d.is_virtual !== null) payload.is_virtual = d.is_virtual;
  if (d.virtual_link) payload.virtual_link = d.virtual_link;
  if (d.currency) payload.currency = d.currency;
  payload.import_source = 'smart_import';
  return payload;
};

export const buildOrganizerPayload = (d: ImportedData) => {
  const payload: Record<string, any> = {};
  if (d.name_en) payload.name = d.name_en;
  if (d.name_ar) payload.name_ar = d.name_ar;
  if (d.description_en) payload.description = d.description_en;
  if (d.description_ar) payload.description_ar = d.description_ar;
  if (d.phone) payload.phone = d.phone;
  if (d.email) payload.email = d.email;
  if (d.website) payload.website = d.website;
  if (d.city_en || d.city_ar) payload.city = d.city_en || d.city_ar;
  if (d.city_ar) payload.city_ar = d.city_ar;
  if (d.country_en || d.country_ar) payload.country = d.country_en || d.country_ar;
  if (d.country_ar) payload.country_ar = d.country_ar;
  if (d.country_code) payload.country_code = d.country_code;
  if (d.full_address_en) payload.address = d.full_address_en;
  if (d.full_address_ar) payload.address_ar = d.full_address_ar;
  if (d.region_en) payload.region = d.region_en;
  if (d.region_ar) payload.region_ar = d.region_ar;
  if (d.street_en) payload.street = d.street_en;
  if (d.street_ar) payload.street_ar = d.street_ar;
  if (d.district_en || d.neighborhood_en) payload.district = d.district_en || d.neighborhood_en;
  if (d.district_ar || d.neighborhood_ar) payload.district_ar = d.district_ar || d.neighborhood_ar;
  if (d.building_number) payload.building_number = d.building_number;
  if (d.floor_number) payload.floor_number = d.floor_number;
  if (d.additional_number) payload.additional_number = d.additional_number;
  if (d.unit_number) payload.unit_number = d.unit_number;
  if (d.short_address) payload.short_address = d.short_address;
  if (d.postal_code) payload.postal_code = d.postal_code;
  if (d.national_address_en) payload.national_address = d.national_address_en;
  if (d.national_address_ar) payload.national_address_ar = d.national_address_ar;
  if (d.fax) payload.fax = d.fax;
  if (d.vat_number) payload.vat_number = d.vat_number;
  if (d.latitude) payload.latitude = d.latitude;
  if (d.longitude) payload.longitude = d.longitude;
  if (d.google_maps_url) payload.google_maps_url = d.google_maps_url;
  if (d.founded_year) payload.founded_year = d.founded_year;
  if (d.logo_url) payload.logo_url = d.logo_url;
  if (d.cover_url) payload.cover_image_url = d.cover_url;
  if (d.gallery_urls?.length) payload.gallery_urls = d.gallery_urls;
  if (d.services_en?.length) payload.services = d.services_en;
  if (d.services_ar?.length) payload.services_ar = d.services_ar;
  if (d.targeted_sectors?.length) payload.targeted_sectors = d.targeted_sectors;
  if (d.categories?.length) payload.categories = d.categories;
  if (d.social_media && Object.values(d.social_media).some(Boolean)) payload.social_links = d.social_media;
  return payload;
};

export const getPayloadForTable = (d: ImportedData, table: TargetTable) => {
  switch (table) {
    case "culinary_entities": return buildEntityPayload(d);
    case "companies": return buildCompanyPayload(d);
    case "establishments": return buildEstablishmentPayload(d);
    case "exhibitions": return buildExhibitionPayload(d);
    case "competitions": return buildCompetitionPayload(d);
    case "organizers": return buildOrganizerPayload(d);
  }
};

export const normalizeWebsiteHost = (value?: string | null) => {
  if (!value) return null;
  const trimmed = value.trim().toLowerCase();
  if (!trimmed) return null;
  try {
    const parsed = new URL(trimmed.startsWith("http") ? trimmed : `https://${trimmed}`);
    return parsed.hostname.replace(/^www\./, "");
  } catch {
    return trimmed
      .replace(/^https?:\/\//, "")
      .replace(/^www\./, "")
      .split("/")[0]
      .trim() || null;
  }
};
